# Generated by Django 4.2.13 on 2024-07-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
    ]
