# Generated by Django 4.2.13 on 2024-07-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursemodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='assessment_methods',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='course/image'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
    ]
