# Generated by Django 5.0.6 on 2024-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_coursemodel_assessment_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/image'),
        ),
    ]
