# Generated by Django 5.0.6 on 2024-07-14 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_reviewmodel_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
