# Generated by Django 5.0.6 on 2024-07-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_reviewmodel_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='data',
            new_name='date',
        ),
    ]
